version: "3.1"

services:
  mongo:
    image: mongo
    command: --smallfiles
    restart: always
    container_name: database
    ports:
      - 27017:27017
    networks: 
      net:
        aliases:
          - database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db_persistence:/data/db
      - ./database/config/:/init
      - ./database/init/:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    restart: always
    container_name: database-interface
    networks: 
      - net
    ports:
      - 9001:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  
  core-users:
    build:
      context: ./backend/core_users/
      dockerfile: Dockerfile
    container_name: core-users
    networks: 
      - net
    ports:
      - 3333:8080
    depends_on:
      - mongo
    environment:
      MONGO_HOST: database
      MONGO_USER: root
      MONGO_PASS: example

volumes:
  db_persistence:

networks: 
  net:
  